<<<<<<< HEAD
# Generated by Django 2.2.7 on 2019-12-18 10:29
=======
# Generated by Django 2.2.7 on 2019-12-21 11:06
>>>>>>> ye le bhai

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
            ],
<<<<<<< HEAD
            options={
                'db_table': 'rxsight"."surgery',
                'managed': True,
            },
=======
>>>>>>> ye le bhai
        ),
    ]
