# Generated by Django 2.2.7 on 2019-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manpower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('type', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
