# Generated by Django 2.2.7 on 2019-12-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0002_manpower'),
    ]

    operations = [
        migrations.CreateModel(
            name='surR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('surgeon', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
