# Generated by Django 2.2.7 on 2019-12-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0003_surr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surr',
            name='surgeon',
        ),
        migrations.CreateModel(
            name='ManR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ranger.surgery')),
            ],
        ),
    ]
