# Generated by Django 2.2.7 on 2019-12-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0004_auto_20191224_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manr',
            name='sid',
            field=models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranger.surgery')),
        ),
    ]
